### ISSUE TITLE
How are you spending talent point between sessions?

### ISSUE THREAD

**Issue by chadsansing** [chadsansing/cineris-campaign#12]
What have you learned on your adventures that might come in handy at dinner with Old Naardo? How are you spending your talent points for your character in ways that make sense with what they've experienced up to now?

**Comment by pfzenke** [comment]
Ob would like to learn Kill Ball.

**Comment by BeardedBurglar** [comment]
I’m fine learning battle bond if someone else wants to

**Comment by cryptomancer-actual** [comment]
I think Psalt is gonna' pick up Bloodletter. His recent battles with a Risk Eater and the Avatar of a God have reminded him of his bloody younger days as the personal bodyguard of a Dwarven mogul.

**Comment by pfzenke** [comment]
@BeardedBurglar I can learn Battle Bond with you if no one else wants to.

**Comment by Claw33** [comment]
I feel like combining my prior knolwedge and my continued study of Mgmentic's tech (with help from Bugs) i have unlocked the Psychometry spell. Additionally my practice and skills with ancient and holy war hammer has earned me Bonecrusher. (4 Pts total)

**Comment by chadsansing** [comment]
Let it be so, @cryptomancer-actual & @Claw33. @pfzenke & @BeardedBurglar, Battlebond sounds appropriate between the two of you, as well. @pfzenke, I think Ob might need some library time and practice to pick up that spell since it's a 3-pointer.

**Comment by pfzenke** [comment]
@chadsansing Sounds good. Thanks Chad!

**Comment by chadsansing** [comment]
Closing.
