### ISSUE TITLE
How are PCs using downtime and preparing to track Jem Brightblade?

### ISSUE THREAD

**Issue by chadsansing** [chadsansing/cineris-campaign#16]
The team has 5 Strategic Asset points, with 3 reserved for a shard storm attack on Stoneshaper Keep. Paslt has suggested using the others on a Ritual Chamber or Dungeon. Gotnafiskr or Naardor can oblige while you're out after Jem.

Given everything PCs have learned, they can take a downtime or two, spend their Talent Points, and share their advancements here.

PCs can also keep researching before they go. Start a new issue per topic, share your query roll, and we'll go from there.

*Session 8 begins at our usual time on June 5th, 2018!*

**Comment by chadsansing** [comment]
@cryptomancer-actual, @pfzenke, @Claw33, @BeardedBurglar, @boristakoi: Just a friendly reminder to spend some Talent Points (varies by PC) and Strategic Assets (5 total; 3 reserved for shard storm attack). Let everyone know what your character has been up to in the safehouse here.

**Comment by BeardedBurglar** [comment]
Kilvar has learned Heightened Senses and Smuggler. That way we can always have a shard if we need to get one past some enemies and as long as I’m paying attention it’s going to be really hard for us to be surprised

**Comment by chadsansing** [comment]
Super handy, @beardedburglar.

**Comment by boristakoi** [comment]
Faelin decides that if we're ever to come face to face with another Risk Eater, he prefers to do so from a distance and decides to put some work in with the worn bow that he received from one of the dwarves in an earlier adventure with an eye towards eventually developing the sniper talent.  Any chance I could spend more than the 2 talent points to earn a rank in that in a short time?  If not, it's something I can do over the course of the next few down times.
I'm also doing some soul-searching as a result of the 'kill all humans' path the group is on.  I'd like to spend some time researching human/dwarf interaction to see if I find motivation for moving ahead or just abandoning it all and focusing on the elven transformation.

**Comment by chadsansing** [comment]
@boristakoi, I think 1 rank is appropriate and what the game allows for in terms of taking Talents - though I may be wrong. I'd suggest Spider or War Dancer on top of Sniper to give you some outs from combat. Make sense?

What is your research question and what are the results of your query roll for it?

**Comment by boristakoi** [comment]
So the final TP spend will be Sniper - 2, Mind Read - 2, and Spider - 2, which uses up what I have accrued.

So for research, I'm viewing the Human/Dwarf struggle as an Israel/Palestine thing and I'm trying to get a feel for who is more in the wrong.  Any history of purges or atrocities, are there any peaceable avenues to resolving the conflict?  How have either side treated the elves in all of this?

**Comment by chadsansing** [comment]
The wasteland dwarves have largely left the elves alone to avoid conflict with the woodland dwarves and to make sure they get raw Soma to process into powerful liquors, etc. The wasteland dwarves openly deride both the elves and their cousins, but they haven't fought them yet. Trade is too important right now.

You read an account from the early days of the occupation detailing how human militias would do extra-judicial killings on Soma dealers and addicts by forced overdose.

**Comment by chadsansing** [comment]
Let's add a dungeon!

**Comment by chadsansing** [comment]
Closing after the session.
