### ISSUE TITLE
Following up on session 9

### ISSUE THREAD

**Issue by chadsansing** [chadsansing/cineris-campaign#18]
Everyone: take 1 TP and spend it while in Portia, if you'd like. Let us know how you use it here.

Psalt, Faelin: take 1 extra TP each.

No SA this session since you get Jem beginning next session.

Please also ask questions, spring theories, and spout lore.

Bonus question: what did you think of the collaborative interstitials?

cc @cryptomancer-actual, @pfzenke, @Claw33, @BeardedBurglar, @boristakoi

**Comment by boristakoi** [comment]
I enjoyed the collaborative interstitial, but was disappointed with how mine played out.  Maybe another chance to shine tonight?

**Comment by boristakoi** [comment]
Having been pressed into service as a battlefield medic on a few occasions, Faelin feels more confident in basic first aid techniques and spends the points on Healer (Ignore 1 botch for all Medicine checks and Alchemy skill checks when making healing potions).

**Comment by chadsansing** [comment]
@boristakoi - for sure; I have a both a contemplative one and a comedic one lined up for you and partners.

Healer talent noted!

**Comment by Claw33** [comment]
@chadsansing where can I get a good recap from last week?

Wally has continued to explore the magical connections to the natural world and has up his communication from bugs and plants to animals learning the Wild Recon spell (3 points)

Also Wally's affable nature has honed his Likability skill ( 1 point)

Wally's ability to talk the party out of jams has sharpened his Silver Tongue (1 point)

**Comment by Claw33** [comment]
@chadsansing is there a hackable version of Wally's character sheet and do you have an updated one?

**Comment by chadsansing** [comment]
@Claw33, here is the recap: https://github.com/chadsansing/cineris-campaign/blob/master/session-notes/session-9.md

Great advances - Wild Recon should be dope in late-campaign play.

**Comment by chadsansing** [comment]
@Claw33, you should be able to download this one and hack it. If not, I can add stuff now for you to reprint.

**Comment by chadsansing** [comment]
Partially updated here: https://github.com/chadsansing/cineris-campaign/blob/master/player-resources/pre-con-pcs/wally-ashsweeper-pc.pdf

@Claw33, you also have Aarok's Sword and some ancient dwarven forge gloves to wear so you can wield it. Stats: are +1 damage, armor piercing, degrades 1 armor point per hit, and macabre - burning hot & scalds wielder unless handled with protective gear.

**Comment by Claw33** [comment]
@chad I also have bone crusher and I think one other spell I added a few weeks ago

**Comment by chadsansing** [comment]
Closing ahead of the next session.
