### ISSUE TITLE
Responses to session 11

### ISSUE THREAD

**Issue by chadsansing** [chadsansing/cineris-campaign#20]
Which way do you go?

- Down the ramp to level 3?
- Down the river into the dark?

Feel free to ask questions!

cc @cryptomancer-actual, @pfzenke, @Claw33, @BeardedBurglar, @boristakoi

**Comment by chadsansing** [comment]
Psalt says river.

**Comment by Claw33** [comment]
Wally votes river

**Comment by pfzenke** [comment]
Ob votes river. Fish hook FTW.

**Comment by chadsansing** [comment]
As does Faelin - the river it is.

Kilvar (@BeardedBurglar), never fear, I will get you back into the narrative post haste.
