### ISSUE TITLE
How are characters using their talent points from session 3?

### ISSUE THREAD

**Issue by chadsansing** [chadsansing/cineris-campaign#7]
Each character has 2 talent points to spend or save. Please share any new talents or spells you think the group should know about before session 4.

**Comment by pfzenke** [comment]
@chadsansing I'm still learning how this process works, but if possible, I'd like to increase my endurance by 2 points. Thanks!

**Comment by chadsansing** [comment]
@pfzenke, I think we need to wait for a larger narrative gap between episodes of the campaign to gain Attribute Ranks (pg. 262); however, you can use (or save) Talent Points now for things like spells (pg. 202) or "Gross" (pg. 188).

**Comment by pfzenke** [comment]
@chadsansing Awesome, thanks. Sorry, I conflated attributes ranks and talents points. I think I'll save my points for now. Thanks buddy.

**Comment by cryptomancer-actual** [comment]
I think I'm going to save the points or just buy more HP.

**Comment by BeardedBurglar** [comment]
I’m going to use my talent points to learn demoitionist so that I can rig up explosive traps.

**Comment by Claw33** [comment]
I am banking mine since I didn't really earn them

**Comment by cryptomancer-actual** [comment]
I'm toying with the idea of having Kilvar teach me Messenger.

In fact, I can see it being useful for multiple people in the party to know this. It's a way for us to do long distance communication outside of our Shards.

**Comment by chadsansing** [comment]
@Claw33, you totally earned them; save or spend away!

**Comment by chadsansing** [comment]
@Claw33 rolled 2 successes. Here are his questions and my answers.

- **Q:** Do I recognize anything from my time at Magmatic? Does my knowledge as an employee let me know anything or interpret anything?
- **A:** Magmatic senior crafter Naardor Gearsmith works on applying ritualistic magic effects to commercial goods (like glowing jacket buttons). The schematic references him: "See Naardor."

- **Q:** Does anything on her hint at the old world or an old text - pre-catastrophe iconography or references?
- **A:** Th word used to describe each little crystal is an old dwarven word for "scale."
