### ISSUE TITLE
How are characters using down time between sessions 3 & 4?

### ISSUE THREAD

**Issue by chadsansing** [chadsansing/cineris-campaign#8]
Let us know what your character gets up to between sessions, as well as what tyour character thinks of the key decisions facing the group from #5.

**Comment by cryptomancer-actual** [comment]
Approximately how many sessions of downtime are we talking here?

**Comment by BeardedBurglar** [comment]
If possible I would like you to gather what I need to rig a bomb as a medium kill trap outside the safe house and set the trap up

**Comment by Claw33** [comment]
I would like to spend te time studying Petra's schematic and researching meaning in my Soma dream about being chased by bionic wolf pack

**Comment by chadsansing** [comment]
@cryptomancer-actual, let's say 1 session while everyone gathers their thoughts and gear at the warehouse.

**Comment by cryptomancer-actual** [comment]
Alright, if he's willing, i'd like to spend my downtime being taught messenger from kilvar

**Comment by chadsansing** [comment]
@cryptomancer-actual, Kilvar may be late to the party this session, so let's mark this as done.

Though you may later remark on learning anything useful from a woodland dwarf.

**Comment by chadsansing** [comment]
@Claw33 - roll Craft vs. 8s. For each success you can ask me a question about the schematic, and I will answer truthfully.

**Comment by chadsansing** [comment]
@Claw33 rolled 2 successes. Here are his questions and my answers.

- **Q:** Do I recognize anything from my time at Magmatic? Does my knowledge as an employee let me know anything or interpret anything?
- **A:** Magmatic senior crafter Naardor Gearsmith works on applying ritualistic magic effects to commercial goods (like glowing jacket buttons). The schematic references him: "See Naardor."

- **Q:** Does anything on her hint at the old world or an old text - pre-catastrophe iconography or references?
- **A:** Th word used to describe each little crystal is an old dwarven word for "scale."
